version: "3"
services:
    site:
        image: starefossen/github-pages:172
        volumes:
            - /Users/hikarumaruyama/src/github.com/hmaruyama/jekyll-test:/usr/src/app
        ports:
            - 4000:4000
